apiRules:
- include:
    uidRegex: ^DocFxForUnity
    type: Namespace
- include:
    uidRegex: ^Global
    type: Namespace
- include:
      uidRegex: ^PirateToolChest
      type: Namespace
- exclude:
    uidRegex: .*
    type: Namespace