# This is a basic workflow to help you get started with Actions

name: Generate Build

on: [push]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Unity - Checkout
      uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: Library
        key: Library-Activ8-poc-GitWorkflowsTests-Windows
        restore-keys: |
          Library-Activ8-poc-GitWorkflowsTests-Windows
          Library-

    - name: Unity - Builder
      uses: webbertakken/unity-builder@v1.4
      with:
        unityVersion: 2019.3.15f1
        targetPlatform: StandaloneWindows
    
#     - name: Publish artifact
#       uses: actions/upload-artifact@v1
#       with:
#         name: Build
#         path: build
    
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        automatic_release_tag: "Latest"
        files: build/Build
  
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Unity - Checkout
      uses: actions/checkout@v2
      
    - name: Unity - Test runner
      uses: webbertakken/unity-test-runner@v1.7
      with:
        unityVersion: 2019.3.15f1
        
    - uses: actions/upload-artifact@v1
      with:
        name: Test results
        path: artifacts
